ALTER SESSION SET "_Oracle_Script"=TRUE;

CREATE USER JAVA_BD
IDENTIFIED BY "ClaseFullStack1-"
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;

GRANT CREATE SESSION, RESOURCE TO JAVA_BD;

ALTER USER JAVA_BD
DEFAULT ROLE RESOURCE;


